config/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls', namespace='news')),
    
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'news'



urlpatterns = [
    path('', views.list_view, name='list_view'),#первая страница
    path('<int:year>/<int:month>/<int:day>/<slug:news>/', views.detail_views, name='news_detail'),#детальная информация
    # path('category/<int:category_id>/', views.detail_category, name='category_posts'),
    # path('news/<int:year>/<int:month>/<int:day>/<slug:news>/', views.post_comment, name='post_comment'),#коментарии
    path('comment/<int:news_id>/', views.post_comment, name='post_comment'),
    path('category/<slug:category_slug>/', views.category_news_detail, name='detail_category'),#детальная информация категории
    # path('registration/', views.register_view, name='registration'),#регистрация пользователя
    # path('search/<slug:category_slug>', views.news_search, name='search_news'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls', namespace='news')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'news'



urlpatterns = [
    path('', views.list_view, name='list_view'),#первая страница
    path('<int:year>/<int:month>/<int:day>/<slug:news>/', views.detail_views, name='news_detail'),#детальная информация
    # path('category/<int:category_id>/', views.detail_category, name='category_posts'),
    # path('news/<int:year>/<int:month>/<int:day>/<slug:news>/', views.post_comment, name='post_comment'),#коментарии
    path('comment/<int:news_id>/', views.post_comment, name='post_comment'),
    path('category/<slug:category_slug>/', views.category_news_detail, name='detail_category'),#детальная информация категории
    # path('registration/', views.register_view, name='registration'),#регистрация пользователя
    # path('search/<slug:category_slug>', views.news_search, name='search_news'),
]

config/news/forms.py
from .models import Comment, UserProfile
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm





class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'text']





class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Enter a valid email address.')


    class Meta:
        model = User
        fields = [
            'username', 'email', 'password1', 'password2'
        ]



class NewsSearchForm(forms.Form):
    search_query = forms.CharField(label='Поиск по заголовку', max_length=100)

news/forms.py
from .models import Comment, UserProfile
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm





class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'text']





class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Enter a valid email address.')


    class Meta:
        model = User
        fields = [
            'username', 'email', 'password1', 'password2'
        ]



class NewsSearchForm(forms.Form):
    search_query = forms.CharField(label='Поиск по заголовку', max_length=100)

config/news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, News, Comment, UserProfile

from .forms import CommentForm, RegistrationForm, NewsSearchForm

from django.views.decorators.http import require_POST
from django.contrib.auth import login

from django.views.generic import View
from django.views.generic import CreateView




def list_view(request):
    """
    функция для отображения категорий и новостей
    """
    latest_news = News.objects.order_by('-pub_date').first()#первая новость
    news_page = News.objects.all()[:4]#новости 4последние
    new = News.objects.all()#все актуальные новости
    cat = Category.objects.all()#все актуальные категории
    week_news = News.get_news_of_the_week(count=4)#топ новостей за неделю
    top_news = News.get_top_news()#топ новости
    return render(request, 'news/post/list.html',
                  {'new': new,
                   'week_news': week_news,
                   'top_news': top_news,
                   'latest_news': latest_news,
                   'news_page ': news_page,
                   'cat': cat}
                  )





def detail_views(request, year, month,day, news):
    """
    детальная информация новости ,те которые публичны
    """
    new_detail = get_object_or_404(News,
                             status=News.Status.PUBLISHED,
                             slug=news,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    category_detail = new_detail.categories.all()#выводит все категории детально
    category_all = Category.objects.all()
    related_news = new_detail.get_related_news()#метод для вывода похожих ровостей по категории
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = new_detail
            new_comment.save()
            return redirect('news:news_detail', year=year, month=month, day=day, news=news)
    else:
        comment_form = CommentForm()
    comments = new_detail.comments.filter(active=True)

    return render(request, 'news/post/detail.html',
                  {'new_detail': new_detail,
                   'category_detail': category_detail,
                   'related_news': related_news,
                   'comments': comments,
                   'comment_form': comment_form,
                   'category_all': category_all}
                  )




def category_news_detail(request, category_slug):
    """
    детальная информация по связанным категориям
    """
    category = get_object_or_404(Category, slug=category_slug)
    news_list = News.objects.filter(categories=category)

    form = NewsSearchForm(request.GET)
    if form.is_valid():
        search_query = form.cleaned_data['search_query']
        # Разбиваем введенную строку на слова
        search_words = search_query.split()

        # Для каждого слова добавляем фильтр
        for word in search_words:
            news_list = news_list.filter(title__icontains=word)

    if request.method == 'POST':
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            return redirect('news:list_view')
    else:
        user_form = RegistrationForm()
    return render(request, 'news/post/category_detail.html',
                  {'category': category, 'news_list': news_list, 'user_form': user_form, 'search_form': form}
                  )




@require_POST
def post_comment(request, news_id):
    """
    коментарии гостей
    """
    news = get_object_or_404(News, id=news_id,
                             status=News.Status.PUBLISHED)
    comment = None  #комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        #создаем обьект Comment не сохраняя его в базе данных
        comment = form.save(commit=False)
        #назначить пост коментария
        comment.news = news
        comment.save()
    return render(request, 'news/post/comment.html',
                  {'news': news, 'form': form, 'comment': comment}
                  )


# @require_POST
# def post_comment(request, news_id):
#     news = get_object_or_404(News, id=news_id, status=News.Status.PUBLISHED)
#     comment = None
#     form = CommentForm(data=request.POST)
#     try:
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.news = news
#             comment.save()
#         else:
#             raise ValueError('Form is valid')
#     except ValueError as e:
#         print(f'Error:{e}')
#         print(form.errors)
#     return render(request, 'news/post/comment.html',
#                       {'news': news, 'form': form, 'comment': comment})

# def register_view(request):
#     """
#     Регистрация
#     """
#     if request.method == 'POST':
#         user_form = RegistrationForm(request.POST)
#         if user_form.is_valid():
#             user = user_form.save()
#             return redirect('news:list_view')
#     else:
#         user_form = RegistrationForm()
#
#     return render(request, 'news/post/registration/registration.html',
#                   {'user_form': user_form}
#                   )
# def news_search(request, category_slug):
#     """
#     Поиск по словам и заголовкам новсти
#     """
#     category = get_object_or_404(Category, slug=category_slug)
#     news_list =  News.objects.filter(categories=category)
#
#     form =NewsSearchForm(request.GET)
#     if form.is_valid():
#         search_query = form.cleaned_data['search_query']
#         # Разбиваем введенную строку на слова
#         news_words = search_query.split()
#
#         # Для каждого слова добавляем фильтр
#         for word in news_words:
#             news_list = news_list.filte(title__icontains=word)
#     return render(request,
#                   'news/post/page_1.html',
#                   {'category': category, 'news_list': news_list, 'form': form})

news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, News, Comment, UserProfile

from .forms import CommentForm, RegistrationForm, NewsSearchForm

from django.views.decorators.http import require_POST
from django.contrib.auth import login

from django.views.generic import View
from django.views.generic import CreateView




def list_view(request):
    """
    функция для отображения категорий и новостей
    """
    latest_news = News.objects.order_by('-pub_date').first()#первая новость
    news_page = News.objects.all()[:4]#новости 4последние
    new = News.objects.all()#все актуальные новости
    cat = Category.objects.all()#все актуальные категории
    week_news = News.get_news_of_the_week(count=4)#топ новостей за неделю
    top_news = News.get_top_news()#топ новости
    return render(request, 'news/post/list.html',
                  {'new': new,
                   'week_news': week_news,
                   'top_news': top_news,
                   'latest_news': latest_news,
                   'news_page ': news_page,
                   'cat': cat}
                  )





def detail_views(request, year, month,day, news):
    """
    детальная информация новости ,те которые публичны
    """
    new_detail = get_object_or_404(News,
                             status=News.Status.PUBLISHED,
                             slug=news,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    category_detail = new_detail.categories.all()#выводит все категории детально
    category_all = Category.objects.all()
    related_news = new_detail.get_related_news()#метод для вывода похожих ровостей по категории
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = new_detail
            new_comment.save()
            return redirect('news:news_detail', year=year, month=month, day=day, news=news)
    else:
        comment_form = CommentForm()
    comments = new_detail.comments.filter(active=True)

    return render(request, 'news/post/detail.html',
                  {'new_detail': new_detail,
                   'category_detail': category_detail,
                   'related_news': related_news,
                   'comments': comments,
                   'comment_form': comment_form,
                   'category_all': category_all}
                  )




def category_news_detail(request, category_slug):
    """
    детальная информация по связанным категориям
    """
    category = get_object_or_404(Category, slug=category_slug)
    news_list = News.objects.filter(categories=category)

    form = NewsSearchForm(request.GET)
    if form.is_valid():
        search_query = form.cleaned_data['search_query']
        # Разбиваем введенную строку на слова
        search_words = search_query.split()

        # Для каждого слова добавляем фильтр
        for word in search_words:
            news_list = news_list.filter(title__icontains=word)

    if request.method == 'POST':
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            return redirect('news:list_view')
    else:
        user_form = RegistrationForm()
    return render(request, 'news/post/category_detail.html',
                  {'category': category, 'news_list': news_list, 'user_form': user_form, 'search_form': form}
                  )




@require_POST
def post_comment(request, news_id):
    """
    коментарии гостей
    """
    news = get_object_or_404(News, id=news_id,
                             status=News.Status.PUBLISHED)
    comment = None  #комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        #создаем обьект Comment не сохраняя его в базе данных
        comment = form.save(commit=False)
        #назначить пост коментария
        comment.news = news
        comment.save()
    return render(request, 'news/post/comment.html',
                  {'news': news, 'form': form, 'comment': comment}
                  )


# @require_POST
# def post_comment(request, news_id):
#     news = get_object_or_404(News, id=news_id, status=News.Status.PUBLISHED)
#     comment = None
#     form = CommentForm(data=request.POST)
#     try:
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.news = news
#             comment.save()
#         else:
#             raise ValueError('Form is valid')
#     except ValueError as e:
#         print(f'Error:{e}')
#         print(form.errors)
#     return render(request, 'news/post/comment.html',
#                       {'news': news, 'form': form, 'comment': comment})

# def register_view(request):
#     """
#     Регистрация
#     """
#     if request.method == 'POST':
#         user_form = RegistrationForm(request.POST)
#         if user_form.is_valid():
#             user = user_form.save()
#             return redirect('news:list_view')
#     else:
#         user_form = RegistrationForm()
#
#     return render(request, 'news/post/registration/registration.html',
#                   {'user_form': user_form}
#                   )
# def news_search(request, category_slug):
#     """
#     Поиск по словам и заголовкам новсти
#     """
#     category = get_object_or_404(Category, slug=category_slug)
#     news_list =  News.objects.filter(categories=category)
#
#     form =NewsSearchForm(request.GET)
#     if form.is_valid():
#         search_query = form.cleaned_data['search_query']
#         # Разбиваем введенную строку на слова
#         news_words = search_query.split()
#
#         # Для каждого слова добавляем фильтр
#         for word in news_words:
#             news_list = news_list.filte(title__icontains=word)
#     return render(request,
#                   'news/post/page_1.html',
#                   {'category': category, 'news_list': news_list, 'form': form})

templates/news/post/category_detail.html
{% extends 'news/base.html' %}

{% block content %}
 <section class="site-section bg-light" id="pricing-section">
      <div class="container">
        <div class="row site-section" id="faq-section">
          <div class="col-12 text-center" data-aos="fade">
            <h2 class="section-title text-primary">{{ category.name }}</h2>
            <p>Новости выбранной категории</p>

          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
           {% for item_news in  news_list%}
                <div class="mb-5" data-aos="fade-up" data-aos-delay="100">
                <a href="{{ item_news.get_absolute_url }}"><h3 class="text-black h4 mb-4">{{ item_news.title}}</h3></a>
                <p>{{  item_news.body }}</p>
                </div>
           {% endfor %}
          </div>
        </div>
      </div>
    </section>
 <section>
     <form method="get" action="{% url 'news:detail_category' category_slug=category.slug %}">
             {{ search_form.as_p }}
        <button type="submit">Искать новость</button>
     </form>
<!--     {% if news_list %}-->
<!--         <h3>Result</h3>-->
<!--     <ul>-->
<!--         {% for news in news_list %}-->
<!--             <li>{{ news.title }}</li>-->
<!--         {% endfor %}-->
<!--     </ul>-->
<!--     {% else %}-->
<!--         <p>No news</p>-->
<!--     {% endif %}-->

 </section>


{% endblock %}

templates/news/post/category_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Category post</title>
</head>
<body>

<h3>{{ category.name }}</h3>
 {% for post in posts %}
   {{ post.title }}
    {{ post.name }}
{% endfor %}

</body>
</html>

templates/news/post/comment.html
{% extends "news/base.html" %}
{% block content %}

    {% if comment %}
       <h2>Add comment</h2>
       <p><a href="{{ news.get_absolute_url }}">Back news</a></p>
    {% else %}
        {% include 'news/post/includes/comment_form.html %}
    {% endif %}
{% endblock %}

templates/news/post/detail.html
{% extends 'news/base.html' %}

{% block content %}
    <div class="site-section-cover overlay inner-page bg-light" style="background-image: url('{{ new_detail.image.url }}')" data-aos="fade">

      <div class="container">
        <div class="row align-items-center justify-content-center text-center">
          <div class="col-lg-10">

            <div class="box-shadow-content">
              <div class="block-heading-1">
                <span class="d-block mb-3 text-white" data-aos="fade-up">{{ new_detail.pub_date }}<span class="mx-2 text-primary">&bullet;</span></span>
                <h1 class="mb-4" data-aos="fade-up" data-aos-delay="100">{{ new_detail.title }}</h1>
              </div>


            </div>
          </div>
        </div>
      </div>

    </div>



    <section class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-8 blog-content">
            <p class="lead">{{ new_detail.title }}</p>
            <p>{{ new_detail.body }}</p>

            <blockquote><p></p></blockquote>

            <p></p>
            <div class="pt-5">
               {% for category in category_detail %}
                  <p>Categories:  <a href="{{ category.get_absolute_url }}">{{ category.name }}</a></p>
               {% endfor %}

            </div>


            <div class="pt-5">
              <h3 class="mb-5">6 Comments</h3>

                <ul class="comment-list">
                  {% for comment in comments %}
                    <li class="comment">
                      <div class="vcard bio">
                        <img src="" alt="Image">
                      </div>
                      <div class="comment-body">
                        <h3>{{ comment.name }}</h3>
                        <div class="meta">{{ comment.updated }}</div>
                        <p>{{ comment.text }}</p>
                      </div>
                    </li>
                  {% endfor %}
                </ul>

              <!-- END comment-list -->

              <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Добавить коментарий</h3>
                <form method="post" action="{{ new_detail.get_absolute_url }}" class="">

                    {% csrf_token %}
                    {{ comment_form.as_p }}

                    <button class="btn btn-primary btn-md text-white" type="submit">Добавить комментарий</button>
                </form>
              </div>
            </div>

          </div>
          <div class="col-md-4 sidebar">
            <div class="sidebar-box">
              <form action="#" class="search-form">
                <div class="form-group">
                  <span class="icon fa fa-search"></span>
                  <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div>
            <div class="sidebar-box">
              <div class="categories">
             {% if category_detail %}
                <h3>Всего катигорий</h3>
                {% for category in category_detail %}
                   <li><a href="#">{{ category.name }}<span></span></a></li>

                {% endfor %}
                   <li><p>{{ category_all.count }}</p><span></span></a></li>

             {% else %}
                    <p>Новость не привязана к категории</p>
             {% endif %}



              </div>
            </div>
            <div class="sidebar-box">
              <img src="images/person_1.jpg" alt="Image" class="img-fluid mb-4 w-50 rounded-circle">
              <h3 class="text-black">About The Author</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
              <p><a href="#" class="btn btn-primary btn-md text-white">Read More</a></p>
            </div>

            <div class="sidebar-box">
              <h3>Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/news/post/list.html
{% extends "news/base.html" %}

{% block content %}
{% if latest_news %}
    <div class="owl-carousel slide-one-item">

      <div class="site-section-cover overlay img-bg-section" style="background-image: url('{{ latest_news.image.url }}'); " >
        <div class="container">
          <div class="row align-items-center justify-content-center text-center">
            <div class="col-md-12 col-lg-8">
              <h1 data-aos="fade-up" data-aos-delay="">{{ latest_news.title }}</h1>
              <p class="mb-5" data-aos="fade-up" data-aos-delay="100">{{ latest_news.body|truncatewords:10 }}</p>
              <p data-aos="fade-up" data-aos-delay="200"><a href="{{ latest_news.get_absolute_url }}" class="btn btn-outline-white border-w-2 btn-md">Смотреть больше</a></p>
            </div>
          </div>
        </div>
      </div>

    </div>
{% endif %}

<div class="site-section" id="blog-section">
      <div class="container">
           <div class="pt-5">
               {% for category in cat %}
                  <p>Категории:  <a href="{% url 'news:detail_category' category_slug=category.slug %} ">{{ category.name }}</a></p>
               {% endfor %}
            </div>
        <div class="row">
          <div class="col-12 text-center mb-5">
            <div class="block-heading-1" data-aos="fade-up" data-aos-delay="">
              <span>Новости Днепра</span>
              <h2>TOP новости недели</h2>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-lg-6" data-aos="fade-up" data-aos-delay="">
            {% for news in top_news|slice:":2"  %}
                <div>
                  <a href="" class="mb-4 d-block"><img src="{{ news.image.url  }}" alt="Image" class="img-fluid rounded"></a>
                  <h2><a href="{{ news.get_absolute_url }}">{{ news.title }}</a></h2>
                  <p class="text-muted mb-3 text-uppercase small"><span class="mr-2">{{ news.pub_date }}</span>
                      {% for category in top_news.categories.all %}
                        By <a href="{{ category.get_absolute_url }}" class="by">{{ category.name }}</a></p>
                      {% endfor %}
                  <p>{{ news.title }}</p>
                  <p><a href="{{ news.get_absolute_url }}">Смотреть новость</a></p>
                </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>


<div class="block__73694 mb-2" id="services-section">
        <div class="container">
             <div class="row">
          <div class="col-12 text-center mb-5">
            <div class="block-heading-1" data-aos="fade-up" data-aos-delay="">
              <span>Новости Днепра</span>
              <h2>Все новости</h2>
            </div>
          </div>
        </div>

          <div class="row d-flex no-gutters align-items-stretch">
           {% for news in new %}

            <div class="col-12 col-lg-6 block__73422" style="background-image: url('{{ news.image.url }}');" data-aos="fade-right" data-aos-delay="">
            </div>

            <div class="col-lg-5 ml-auto p-lg-5 mt-4 mt-lg-0" data-aos="fade-left" data-aos-delay="">
              <h2 class="mb-3 text-black">{{ news.name }}</h2>
              <a href="{{ news.get_absolute_url }}"><p>{{ news.title }}</p></a>

              <p>{{ news.body }}</p>
              <p>{{ news.pub_date}}</p>
              <p> Тэги: {{ news.tags.all|join:','}}</p>
            </div>
          {% endfor %}

          </div>
        </div>
</div>
<!--<div class="site-section" id="blog-section">-->
<!--      <div class="container">-->
<!--        <div class="row">-->
<!--          <div class="col-12 text-center mb-5">-->
<!--            <div class="block-heading-1" data-aos="fade-up" data-aos-delay="">-->
<!--              <span>Новости Днепра</span>-->
<!--              <h2>новости недели</h2>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--          <div class="col-md-6 col-lg-6" data-aos="fade-up" data-aos-delay="">-->
<!--            {% for week in week_news %}-->
<!--                <div>-->
<!--                  <a href="single.html" class="mb-4 d-block"><img src="{{ news.image.url  }}" alt="Image" class="img-fluid rounded"></a>-->
<!--                  <h2><a href="single.html">How To Find Gold In Mining</a></h2>-->
<!--                  <p class="text-muted mb-3 text-uppercase small"><span class="mr-2">{{ week.pub_date }}</span>-->
<!--                      {% for category in week_news.categories.all %}-->
<!--                        By <a href="single.html" class="by">{{ category.name }}</a></p>-->
<!--                      {% endfor %}-->
<!--                  <p>{{ week.title }}</p>-->
<!--                  <p><a href="single.html">Read More</a></p>-->
<!--                </div>-->
<!--            {% endfor %}-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->

 <section class="site-section bg-light" id="pricing-section">
      <div class="container">
        <div class="row site-section" id="faq-section">
          <div class="col-12 text-center" data-aos="fade">
            <h2 class="section-title text-primary">Актуальное сейчас</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
           {% for item in new|slice:":4"  %}
                <div class="mb-5" data-aos="fade-up" data-aos-delay="100">
                <a href="{{ item.get_absolute_url }}"><h3 class="text-black h4 mb-4">{{ item.title}}</h3></a>
                <p>{{  item.body }}</p>
                </div>
           {% endfor %}
          </div>
        </div>
      </div>
    </section>

{% endblock %}

templates/news/post/page1.html
{% extends 'news/base.html' %}

{% block content %}
<form method="get" action="{% url 'news:search_news' category_slug=category.slug %}">
    {{ form.as_p }}
    <button type="submith">Искать новость</button>
</form>

{% endblock %}